# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  apigateway:
    image: apigateway
    build:
      context: ..
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - 5111:5111
