version: '3.8'

services:
  authservice:
    build: 
      context: ..
      dockerfile: src/AuthService/Dockerfile
    ports:
      - "5079:80"
      - "7135:443"
    env_file:
      - .env.local
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
      - redis

  itemservice:
    build: 
      context: ..
      dockerfile: src/ItemService/Dockerfile
    ports:
      - "7136:80"
      - "7137:443"
    env_file:
      - .env.local
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
      - redis

  apigateway:
    build:
      context: ..
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5166:80"
      - "7245:443"
    env_file:
      - .env.local
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - authservice
      - itemservice

  db:
    image: postgres:16
    container_name: UserPGDB
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
